### PR TITLE
fix namespace active status

### PR DESCRIPTION
**Pull request by SehKeat**
fix namespace active status when expired to red cross and enable extend

### CODE REVIEW

**Review by sleepyOwl14 — CHANGES_REQUESTED** [review]
wrongly done

**Comment by sleepyOwl14** [comment]
please remove unused import and compare namespace active directly at the vue page

**Comment by SehKeat** [comment]
changes done on the vue page

**Comment by sleepyOwl14** [comment]
directly assign the boolean comparison return value to the `isActive` property

**Review by anakin001 — APPROVED** [review]

**Review by sleepyOwl14 — APPROVED** [review]

**Pull request merged**
