### PR TITLE
increase font notification

### PR DESCRIPTION
**Pull request by faiqahjasmi97**

### CODE REVIEW

**Review by sleepyOwl14 — CHANGES_REQUESTED** [review]
what is this classname with `...` ? not sure what are you trying to do.

CSS Naming rules:
- Must begin with a letter A-Z or a-z
- Can be followed by: letters (A-Za-z), digits (0-9), hyphens ("-"), and underscores ("_")

**Comment by SehKeat** [comment]
Changed to only show first 7 and last 7 characters only

**Comment by shinneng** [comment]
> Changed to only show first 7 and last 7 characters only

to attach screenshot

**Comment by SehKeat** [comment]
Screenshot 2023-01-12 135741
Changed to similar format in transaction tab

**Review by shinneng — APPROVED** [review]

**Review by shinneng — APPROVED** [review]

**Review by sleepyOwl14 — APPROVED** [review]

**Pull request merged**
