### PR TITLE
Fix duplicate data in dashboard page

### PR DESCRIPTION
**Pull request by Ghost-Slime**

### CODE REVIEW

**Comment by sleepyOwl14** [comment]
how come the asset ID will duplicate in the account ?

**Comment by Ghost-Slime** [comment]
Sorry, I unable to find the cause of why the asset ID will duplicate in the account.

**Comment by Ghost-Slime** [comment]
> how come the asset ID will duplicate in the account ?

Sorry, I unable to find the cause of why the asset ID will duplicate in the account.

**Comment by sleepyOwl14** [comment]
I found out the issue, will close this PR and fix it with another PR

**Pull request closed without merging**
